\c "CrudTaskDb"

CREATE TABLE "Customers" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" VARCHAR(50) NOT NULL,
    "LastName" VARCHAR(50) NOT NULL,
    "PhoneNumber" VARCHAR(20) NOT NULL,
    "Email" VARCHAR(50) NOT NULL UNIQUE,
    "DateOfBirth" Date NOT NULL,
    "BankAccountNumber" VARCHAR(20) NOT NULL
);

INSERT INTO "Customers" 
("FirstName", "LastName", "PhoneNumber", "Email", "DateOfBirth", "BankAccountNumber")
VALUES 
('John', 'Doe', '+14844458571','John@Doe.com', '1955-01-01', '123456789');

INSERT INTO "Customers" 
("FirstName", "LastName", "PhoneNumber", "Email", "DateOfBirth", "BankAccountNumber")
VALUES 
('Mohammad','Modarreszadeh','+989393639116','modarreszadehmohammad@gmail.com','2001-03-03','987654321');