version: "3.4"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=CrudTaskDb
    # volumes:
    # - ./CrudTest.Domain/Script/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5430:5432

  web:
    image: web
    container_name: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: CrudTest.Presentation/Server/Dockerfile
    ports:
      - 5005:80
    depends_on:
      - postgres
